// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfq_lIii-Em0QBTsqEF4iHo86Krx7wsd8',
    appId: '1:939246492046:web:7ab48f9c9a3f4ff395acdf',
    messagingSenderId: '939246492046',
    projectId: 'chat-app-aa63e',
    authDomain: 'chat-app-aa63e.firebaseapp.com',
    storageBucket: 'chat-app-aa63e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCanu4c4EvAGPmcgayrhd7P7VPqQxBz6n4',
    appId: '1:939246492046:android:7b75f5417a08056195acdf',
    messagingSenderId: '939246492046',
    projectId: 'chat-app-aa63e',
    storageBucket: 'chat-app-aa63e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8eDjx4vL0Q0e-ulWfcfruXpchqLOY7zo',
    appId: '1:939246492046:ios:c7dc59a782617fd595acdf',
    messagingSenderId: '939246492046',
    projectId: 'chat-app-aa63e',
    storageBucket: 'chat-app-aa63e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8eDjx4vL0Q0e-ulWfcfruXpchqLOY7zo',
    appId: '1:939246492046:ios:c7dc59a782617fd595acdf',
    messagingSenderId: '939246492046',
    projectId: 'chat-app-aa63e',
    storageBucket: 'chat-app-aa63e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfq_lIii-Em0QBTsqEF4iHo86Krx7wsd8',
    appId: '1:939246492046:web:d4ad18bfdc7d9f2595acdf',
    messagingSenderId: '939246492046',
    projectId: 'chat-app-aa63e',
    authDomain: 'chat-app-aa63e.firebaseapp.com',
    storageBucket: 'chat-app-aa63e.firebasestorage.app',
  );

}